#!/usr/bin/env bash
#
# Generate a small deterministic directory tree and build .etr / .idx
# fixtures from it using parallel-idx.
#
# Usage:
#   ./generate_fixtures.sh [path-to-parallel-idx]
#
# If no path is given, we look for it in ../../target/release/parallel-idx,
# then ../../target/debug/parallel-idx, then $PATH.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FIXTURE_DIR="$SCRIPT_DIR"
TREE_DIR="$FIXTURE_DIR/sample_tree"

# --- locate parallel-idx --------------------------------------------------

find_parallel_idx() {
    if [[ -n "${1:-}" ]]; then
        echo "$1"
        return
    fi

    local repo_root
    repo_root="$(cd "$SCRIPT_DIR/../../.." && pwd)"

    for candidate in \
        "$repo_root/target/release/parallel-idx" \
        "$repo_root/target/debug/parallel-idx" \
    ; do
        if [[ -x "$candidate" ]]; then
            echo "$candidate"
            return
        fi
    done

    if command -v parallel-idx &>/dev/null; then
        echo "parallel-idx"
        return
    fi

    echo "ERROR: could not find parallel-idx binary." >&2
    echo "  Build it with: cargo build --release" >&2
    echo "  Or pass the path: $0 /path/to/parallel-idx" >&2
    exit 1
}

PIDX="$(find_parallel_idx "${1:-}")"
echo "Using parallel-idx: $PIDX"

# --- create a small deterministic tree ------------------------------------

rm -rf "$TREE_DIR"
mkdir -p "$TREE_DIR"

# A few top-level files
echo "Hello, world!"           > "$TREE_DIR/hello.txt"
echo '{"key": "value"}'        > "$TREE_DIR/data.json"
dd if=/dev/urandom of="$TREE_DIR/random.bin" bs=1024 count=16 2>/dev/null

# A nested directory with files
mkdir -p "$TREE_DIR/docs/notes"
echo "# README"                > "$TREE_DIR/docs/README.md"
echo "Some notes here."        > "$TREE_DIR/docs/notes/note1.txt"
echo "More notes."             > "$TREE_DIR/docs/notes/note2.txt"

# Another branch
mkdir -p "$TREE_DIR/src/lib"
echo 'fn main() {}'            > "$TREE_DIR/src/main.rs"
echo 'pub fn lib() {}'         > "$TREE_DIR/src/lib/mod.rs"

# An empty directory
mkdir -p "$TREE_DIR/empty"

echo "Created sample tree at: $TREE_DIR"
echo "  Files: $(find "$TREE_DIR" -type f | wc -l | tr -d ' ')"
echo "  Dirs:  $(find "$TREE_DIR" -type d | wc -l | tr -d ' ')"

# --- generate .etr (empty tree) -------------------------------------------

ETR="$FIXTURE_DIR/sample.etr"
echo "Generating empty tree: $ETR"
"$PIDX" -e -f "$ETR" "$TREE_DIR"

# --- generate .idx (complete index with hashes) ----------------------------

IDX="$FIXTURE_DIR/sample.idx"
echo "Generating complete index: $IDX"
"$PIDX" -n 2 -f "$IDX" -t "$ETR"

# --- also dump a JSON reference for cross-checking (if supported) ----------
# parallel-idx may or may not have --json; skip if not available
if "$PIDX" --help 2>&1 | grep -q -- '--json\|--dump-json'; then
    echo "Generating JSON reference..."
    "$PIDX" --json -t "$ETR" > "$FIXTURE_DIR/sample.json" 2>/dev/null || true
fi

# --- write a manifest so tests know what to expect -------------------------

cat > "$FIXTURE_DIR/manifest.txt" <<EOF
# Auto-generated by generate_fixtures.sh — do not edit
tree_dir=$TREE_DIR
etr=$ETR
idx=$IDX
file_count=$(find "$TREE_DIR" -type f | wc -l | tr -d ' ')
dir_count=$(find "$TREE_DIR" -type d -mindepth 1 | wc -l | tr -d ' ')
files=$(find "$TREE_DIR" -type f | sort | tr '\n' '|')
EOF

echo ""
echo "Done. Fixtures written to: $FIXTURE_DIR"
echo "  sample.etr  — empty tree"
echo "  sample.idx  — complete index with hashes"
echo "  manifest.txt — expected values for tests"
