"""
Integration tests that run against real .etr / .idx fixtures generated by
parallel-idx.

These tests are skipped if the fixture files don't exist. Run
``generate_fixtures.sh`` (or the CI workflow) to create them.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from ptar_index import EntryKind, load_index, describe_raw

# ---------------------------------------------------------------------------
# Fixture discovery
# ---------------------------------------------------------------------------

FIXTURE_DIR = Path(__file__).parent / "fixtures"
SAMPLE_ETR = FIXTURE_DIR / "sample.etr"
SAMPLE_IDX = FIXTURE_DIR / "sample.idx"
MANIFEST = FIXTURE_DIR / "manifest.txt"

fixtures_exist = SAMPLE_ETR.exists() and SAMPLE_IDX.exists()

skip_reason = (
    "Fixtures not found. Run: "
    "cd python/tests/fixtures && bash generate_fixtures.sh"
)

pytestmark = pytest.mark.skipif(not fixtures_exist, reason=skip_reason)


def _load_manifest() -> dict:
    """Parse the key=value manifest written by generate_fixtures.sh."""
    if not MANIFEST.exists():
        return {}
    d: dict = {}
    for line in MANIFEST.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, val = line.partition("=")
        d[key.strip()] = val.strip()
    return d


@pytest.fixture(scope="module")
def manifest():
    return _load_manifest()


@pytest.fixture(scope="module")
def etr_index():
    return load_index(SAMPLE_ETR)


@pytest.fixture(scope="module")
def idx_index():
    return load_index(SAMPLE_IDX)


# ---------------------------------------------------------------------------
# Tests: .etr (empty tree)
# ---------------------------------------------------------------------------

class TestEmptyTree:
    def test_loads(self, etr_index):
        assert etr_index is not None
        assert etr_index.file_type == "etr"

    def test_root_is_dir(self, etr_index):
        assert etr_index.root.is_dir

    def test_root_name(self, etr_index):
        assert etr_index.root.name == "sample_tree"

    def test_has_children(self, etr_index):
        assert len(etr_index.root) > 0

    def test_known_dirs_exist(self, etr_index):
        """We know the fixture has docs/, src/, empty/."""
        child_names = {c.name for c in etr_index.root}
        assert "docs" in child_names
        assert "src" in child_names
        assert "empty" in child_names

    def test_known_files_exist(self, etr_index):
        child_names = {c.name for c in etr_index.root}
        assert "hello.txt" in child_names
        assert "data.json" in child_names
        assert "random.bin" in child_names

    def test_nested_resolve(self, etr_index):
        note = etr_index.resolve("docs/notes/note1.txt")
        assert note is not None
        assert note.name == "note1.txt"

    def test_etr_has_no_hashes(self, etr_index):
        """Empty trees should not have hashes populated."""
        for entry in etr_index.walk_files():
            # hash may or may not be None depending on version,
            # but most .etr files leave it empty
            pass  # just confirm we can walk without errors

    def test_file_count_matches_manifest(self, etr_index, manifest):
        if "file_count" not in manifest:
            pytest.skip("manifest missing file_count")
        expected = int(manifest["file_count"])
        actual = sum(1 for _ in etr_index.walk_files())
        assert actual == expected

    def test_dir_count_matches_manifest(self, etr_index, manifest):
        if "dir_count" not in manifest:
            pytest.skip("manifest missing dir_count")
        expected = int(manifest["dir_count"])
        # walk_dirs includes root, manifest doesn't (mindepth 1)
        actual = sum(1 for _ in etr_index.walk_dirs()) - 1
        assert actual == expected


# ---------------------------------------------------------------------------
# Tests: .idx (complete index)
# ---------------------------------------------------------------------------

class TestCompleteIndex:
    def test_loads(self, idx_index):
        assert idx_index is not None
        assert idx_index.file_type == "idx"

    def test_root_is_dir(self, idx_index):
        assert idx_index.root.is_dir

    def test_root_has_hash(self, idx_index):
        assert idx_index.root_hash is not None
        # SHA-256 hex = 64 chars
        assert len(idx_index.root_hash) == 64

    def test_root_has_size(self, idx_index):
        assert idx_index.root.size is not None
        assert idx_index.root.size > 0

    def test_file_count_matches_manifest(self, idx_index, manifest):
        if "file_count" not in manifest:
            pytest.skip("manifest missing file_count")
        expected = int(manifest["file_count"])
        actual = sum(1 for _ in idx_index.walk_files())
        assert actual == expected

    def test_files_have_hashes(self, idx_index):
        """In a complete index, every file should have a hash."""
        for f in idx_index.walk_files():
            assert f.hash_hex is not None, f"missing hash for {f.path}"
            assert len(f.hash_hex) == 64, f"bad hash length for {f.path}"

    def test_files_have_sizes(self, idx_index):
        for f in idx_index.walk_files():
            assert f.size is not None, f"missing size for {f.path}"
            assert f.size >= 0, f"negative size for {f.path}"

    def test_known_file_size(self, idx_index):
        """hello.txt contains 'Hello, world!\\n' = 14 bytes."""
        hello = idx_index.resolve("hello.txt")
        assert hello is not None
        assert hello.size == 14

    def test_dirs_have_aggregate_counts(self, idx_index):
        assert idx_index.root.file_count is not None
        assert idx_index.root.file_count > 0

    def test_all_paths_under_root(self, idx_index):
        root_path = idx_index.root.path
        for entry in idx_index.walk():
            if entry is idx_index.root:
                continue
            assert entry.path.startswith(root_path), (
                f"{entry.path} not under {root_path}"
            )

    def test_parent_pointers_consistent(self, idx_index):
        for entry in idx_index.walk():
            for child in entry.children:
                assert child.parent is entry, (
                    f"{child.path}'s parent is not {entry.path}"
                )


# ---------------------------------------------------------------------------
# Tests: .etr vs .idx consistency
# ---------------------------------------------------------------------------

class TestEtrVsIdx:
    def test_same_file_count(self, etr_index, idx_index):
        etr_files = sum(1 for _ in etr_index.walk_files())
        idx_files = sum(1 for _ in idx_index.walk_files())
        assert etr_files == idx_files

    def test_same_file_paths(self, etr_index, idx_index):
        etr_paths = {e.path for e in etr_index.walk_files()}
        idx_paths = {e.path for e in idx_index.walk_files()}
        assert etr_paths == idx_paths

    def test_same_dir_paths(self, etr_index, idx_index):
        etr_paths = {e.path for e in etr_index.walk_dirs()}
        idx_paths = {e.path for e in idx_index.walk_dirs()}
        assert etr_paths == idx_paths

    def test_idx_has_more_metadata(self, etr_index, idx_index):
        """The .idx should have hashes; the .etr may not."""
        idx_hashes = sum(1 for f in idx_index.walk_files() if f.hash_hex)
        assert idx_hashes > 0


# ---------------------------------------------------------------------------
# Tests: describe_raw doesn't crash on real files
# ---------------------------------------------------------------------------

class TestDescribeRaw:
    def test_etr(self):
        desc = describe_raw(SAMPLE_ETR, max_depth=2)
        assert len(desc) > 0

    def test_idx(self):
        desc = describe_raw(SAMPLE_IDX, max_depth=2)
        assert len(desc) > 0
